#! /usr/bin/env python3

import argparse
import os
import pathlib

from build_kernel import Builder

def build_cfg(cfg):
  cfg_path = os.path.join(str(pathlib.Path.home()), 'ss/build_kernel/configs', cfg)
  builder = Builder(cfg_path, generate_compile_db=True, generate_pkg=False,
                    fail_on_stderr=True)
  builder.do_build()

def main():
  parser = argparse.ArgumentParser(description='Build drm-misc configs')
  parser.add_argument('--nodocs', default=False, action='store_true',
                      help='Skip sphinx build')
  parser.add_argument('--noarm', default=False, action='store_true',
                      help='Skip arm builds')
  parser.add_argument('--nox86', default=False, action='store_true',
                      help='Skip x86 builds')
  parser.add_argument('--noall', default=False, action='store_true',
                      help='Skip all*config builds')
  args = parser.parse_args()

  if args.noarm == False:
    build_cfg('drm-misc-arm.ini')
    build_cfg('drm-misc-arm64.ini')

  if args.nox86 == False:
    build_cfg('drm-misc-x86.ini')
    build_cfg('drm-misc-x86-nofbdev.ini')

  if args.nodocs == False:
    build_cfg('drm-misc-htmldocs.ini')

  if args.noall == False:
    build_cfg('allmodconfig_arm64.ini')
    build_cfg('allyesconfig_arm64.ini')
    build_cfg('allmodconfig_arm.ini')
    build_cfg('allyesconfig_arm.ini')


if __name__ == '__main__':
  main()
